---
title: "NFL-seeding"
author: "Gregory J. Matthews"
date: "2023-01-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## NFL playoff qualification

The National Football League (NFL) determines the champion of their league each year to be the team that wins the Super Bowl.  In order to get to the Super Bowl, a team must first qualify for the playoffs with the NFL playoffs consisting of a single elimination tournament with the teams reseeded after each round.  Teams qualify for the playoffs by satisfying some criteria for qualification based on the results of their regular season play with number of wins being the most important followed by a series of tie breakers.  

In 2002, the NFL added the Houston Texans moving from 31 teams to 32 teams and moved from three divisions of 5 teams (one division had 6 teams) per conference to 4 divisions of 4 teams per conference.  From 2002 to the 2019, the teams that qualified for the playoffs were, in each conference, the 4 division winners and two wild card teams (i.e. the non division winners with the best records) for 6 total.  In the 2020 playoffs a third playoff team was added for 7 total from each conference.  

As a result of these rules for qualification and the scheduling method for the NFL, it is possible for teams with a losing record to get into the playoffs if they beat the other three teams in their division.  While this was a theoretical possibility starting in 2002, it did not occur until the 2010 season when the Seattle Seahawks won their division with a record of 7-9 (and notably won their first round playoff game...).  Since then it has happened three additional times (2014, Carolina Panthers, 7-8-1; 2020, Washington Football Team, 7-9; 2022, Tampa Bay Buccaneers, 8-9).  (Note: In 2008 and 2011 there were division winners that went 8-8, San Diego Chargers and Denver Broncos, respectively).

In the NFL, the team with the higher seed in a game will always host the game.  And seeding works as follows: 1) The four division winners in each conference will be seeded 1 through 4 based on their records and tie breaking procedures. 2) Seed 5 and 6 (and now 7) are given to the three wild card teams based on records and tie breakers.  

This means that the 5 seed, the wild card team with the most wins, sometimes has more wins than the 4 seed, but the 4 seed still gets the higher seed allowing them to host the game against a wild card team.  

In this manuscript, we explore different methods of seeding and different tournament structures to make the playoffs more "fair" while still trying to avoid geographical "concentrations" of playoff teams.  

## Qualifying rules.  
Matthews System: It's real life but division winners have to be over .500. If division winner is not over .500, there is another wild card team.  

## Seeding structures
- Ignore everything top 14 teams period (1-14 ignoring all structure) 
- 1-7 within each conference ignoring divisons. 
- Stuart system: In each conference the 1-2 are the "sub-conference" champions. and then 3-7 are wild cards.  
- Stuart system where seeding is based only on wins.  
- Just 8 divisiosn no conferences.  8 division winners and 6 wild cards ignoring conferences.  (Division winners 1-8, and then wild card teams are the rest)
- All division winners and 3 wild cards teams seeded by record.  
- Real playoff scenario

- Subdivisoons and top 7 sub division winners qualify and seeding is based on record.  


## Playoff structures
- single elimination fixed straight bracket  
- single elimination with re-seeding after every round. 
- regular seeding but HFA is determined by record.  Same record goes to better seed.  
- Higher seed gets to "choose".  
    - They always choose the worse team
    - There is some probability of choosing a team based on proportion to the thetas.  
- Aussie Rules football structure
- PBA ladder structure.  
- Japanese Basebakll, Korean Baseball. 
- Double elimination tournament structure.  
  - True double elimination 
  - Modified double elimination.  
- Some kind of round robin. 
- Little league world series "double elimination". 
- Repechage like in Olympic wrestling.  


https://www.tandfonline.com/doi/abs/10.1057/palgrave.jors.2600330
https://journals.sagepub.com/doi/pdf/10.1177/1527002510363103
https://journals.humankinetics.com/view/journals/ijsnem/29/4/article-p441.xml
https://www.tandfonline.com/doi/abs/10.1080/13606710110117023







 


